services:

  nginx:
    image: nginx:alpine
    container_name: finix_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - finix_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: finix_php
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    networks:
      - finix_network

  mysql:
    image: mysql:8.0
    container_name: finix_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: finix_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: finix
      MYSQL_PASSWORD: finix123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - finix_network

  redis:
    image: redis:alpine
    container_name: finix_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - finix_network

  node:
    image: node:20-alpine
    container_name: finix_node
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - finix_network

volumes:
  mysql_data:
    driver: local

networks:
  finix_network:
    driver: bridge